controller_list:
  - name: fake_gripper_controller
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
  - name: fake_arm_1_joints_controller
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5